# Generated by Django 3.1.13 on 2021-11-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='diaganotico',
            field=models.TextField(blank=True, default=True, null=True),
        ),
    ]
