# Generated by Django 3.1.13 on 2021-11-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0002_auto_20211128_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='diaganotico',
            new_name='diagnostico',
        ),
    ]
