# Generated by Django 3.1.13 on 2021-11-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0003_auto_20211128_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='diagnostico',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
