# Generated by Django 3.1.13 on 2021-11-30 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutri_app', '0004_auto_20211128_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBiomedicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.JSONField(default=dict)),
                ('ginecologicos', models.JSONField(default=dict)),
                ('medicamentos', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_paciente_datos_biomedicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
