# Generated by Django 3.1.13 on 2021-12-03 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutri_app', '0007_auto_20211203_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuenciadeconsumo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_paciente_frecuencia_consumo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=30, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_paciente_deportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
