# Generated by Django 3.1.13 on 2021-12-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0008_auto_20211203_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deporte',
            name='alimento',
        ),
        migrations.RemoveField(
            model_name='deporte',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='deporte',
            name='observacion',
        ),
        migrations.AddField(
            model_name='deporte',
            name='deporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deporte',
            name='dias_descanso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deporte',
            name='dias_semanas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deporte',
            name='duraciion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deporte',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deporte',
            name='horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deporte',
            name='merienda_post',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deporte',
            name='merienda_pre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
