# Generated by Django 3.1.13 on 2021-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0010_suplemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbiomedicos',
            name='actividad_fisica',
            field=models.JSONField(default=dict),
        ),
    ]
