# Generated by Django 3.1.13 on 2021-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0012_auto_20211203_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
