# Generated by Django 3.1.13 on 2021-12-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0013_cita_cancelada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('kcal', models.CharField(blank=True, max_length=50, null=True)),
                ('veces_por_dia', models.CharField(blank=True, max_length=50, null=True)),
                ('dias_a_la_semana', models.CharField(blank=True, max_length=50, null=True)),
                ('dosis', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
