# Generated by Django 3.1.13 on 2021-12-05 17:39

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0014_tipocomida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_menu', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipocomida',
            name='dias_a_la_semana',
        ),
        migrations.RemoveField(
            model_name='tipocomida',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='tipocomida',
            name='veces_por_dia',
        ),
        migrations.AddField(
            model_name='tipocomida',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MenuLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', model_utils.fields.StatusField(choices=[('Comida 1', 'Comida 1'), ('Comida 2', 'Comida 2'), ('Comida 3', 'Comida 3'), ('Comida 4', 'Comida 4'), ('Comida 5', 'Comida 5'), ('Comida 6', 'Comida 6'), ('Colación', 'Colación')], default='Comida 1', max_length=100, no_check_for_status=True)),
                ('tipo_comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_menu_lines', to='nutri_app.tipocomida')),
            ],
        ),
    ]
