# Generated by Django 3.1.13 on 2021-12-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutri_app', '0015_auto_20211205_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuline',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nutri_menu_lines', to='nutri_app.menu'),
        ),
        migrations.AlterField(
            model_name='menuline',
            name='tipo_comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutri_menu_tipo_comidas', to='nutri_app.tipocomida'),
        ),
    ]
