# Generated by Django 3.1.13 on 2021-11-19 15:24

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211119_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Masculino', max_length=100, no_check_for_status=True),
        ),
    ]
