# Generated by Django 3.1.13 on 2021-11-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211120_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ocupación',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ocupación'),
        ),
    ]
